<a href="https://colab.research.google.com/github/ainsley-snell/Data_Mining_CS290/blob/main/chapt2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import tiktoken

raw_text="This is my dog Hazel"
tokenizer= tiktoken.get_encoding("gpt2")
enc_text= tokenizer.encode(raw_text)
print(enc_text)

vocab_size= 4
output_dim= 8
inputs= torch.nn.Embedding(vocab_size, output_dim)
print(inputs.weight)

inputs= inputs.weight.data
inputs

inputs.shape
for row in inputs:
    print(row.tolist())

x= torch.Tensor([1.1,2.3])
y= torch.Tensor([3.4,-2.1])

1.1 * 3.4 + (2.3 * -2.1)

torch.dot(x,y)

query= inputs[2]
print(query)

for i in range(len(inputs)):
    print(torch.dot(query,inputs[i]))

attention_scores_2= torch.zeros(len(inputs))
for i in range(len(inputs)):
    attention_scores_2[i]=torch.dot(query,inputs[i])
print(attention_scores_2)

#normalize attention scores using the softmax funtion to become weights:
#def softmax(x):
#    torch.exp(x)/ torch.exp(x).sum()

attention_weights_2= torch.softmax(attention_scores_2, dim=0)
attention_weights_2.sum()

#use weights to create context vector
context_vector_2= torch.zeros(query.shape)
for i in range(len(attention_weights_2)) :
    context_vector_2 += attention_weights_2[i]* inputs[i]
context_vector_2


[1212, 318, 616, 3290, 42805]
Parameter containing:
tensor([[ 0.8255, -0.9730,  0.3501,  0.9520,  0.1073,  1.1137, -1.1786,  0.6746],
        [ 0.9046,  0.0460,  0.9300,  0.4690, -0.8641,  0.4575,  1.3406, -0.7128],
        [-0.6020, -1.7164, -0.6697, -0.0984, -0.0059, -0.9036,  0.0898, -0.5996],
        [ 1.2326, -1.4545, -2.0221,  0.6826,  0.7042,  0.6563, -0.2528,  1.2570]],
       requires_grad=True)
[0.8254863619804382, -0.9730457067489624, 0.3501078486442566, 0.9519725441932678, 0.10733524709939957, 1.1137068271636963, -1.1786366701126099, 0.6746042370796204]
[0.9046087861061096, 0.04602408781647682, 0.9299994707107544, 0.4689948856830597, -0.864142894744873, 0.4574982821941376, 1.340553641319275, -0.7127615809440613]
[-0.601959764957428, -1.7164299488067627, -0.6697110533714294, -0.09836871922016144, -0.005870187189429998, -0.9035903811454773, 0.08981180936098099, -0.599642276763916]
[1.232577919960022, -1.4545302391052246, -2.02207350730896, 0.6825509667396545, 0.70423185825347

tensor([ -2.5221, -10.3229,  -7.9962,  -0.5292,   2.0698,  -4.6549,  -0.7305,
         -0.5036])

In [6]:
#get all attention scores via matrix multiplication (inputs.T is transposed inputs)
attention_scores= inputs @ inputs.T
attention_scores

tensor([[ 5.7532, -0.1701, -0.6722,  4.3272],
        [-0.1701,  5.1665, -1.1530, -2.0556],
        [-0.6722, -1.1530,  4.9508,  1.6680],
        [ 4.3272, -2.0556,  1.6680, 10.7603]])

In [8]:
attention_weights= torch.softmax(attention_scores, dim=-1)
attention_weights

tensor([[8.0350e-01, 2.1505e-03, 1.3016e-03, 1.9305e-01],
        [4.7775e-03, 9.9271e-01, 1.7878e-03, 7.2501e-04],
        [3.4635e-03, 2.1414e-03, 9.5843e-01, 3.5964e-02],
        [1.6046e-03, 2.7126e-06, 1.1234e-04, 9.9828e-01]])

In [9]:
attention_weights[0].sum()

tensor(1.)

In [10]:
context_vectors=attention_weights @ inputs
context_vectors

tensor([[ 0.9024, -1.0648, -0.1079,  0.8976,  0.2203,  1.0214, -0.9928,  0.7824],
        [ 0.9018,  0.0369,  0.9222,  0.4704, -0.8568,  0.4583,  1.3251, -0.7045],
        [-0.5278, -1.7007, -0.7114, -0.0654,  0.0182, -0.8376,  0.0758, -0.5287],
        [ 1.2317, -1.4538, -2.0181,  0.6829,  0.7032,  0.6569, -0.2543,  1.2559]])