<a href="https://colab.research.google.com/github/ainsley-snell/Data_Mining_CS290/blob/main/normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [5]:
outputs= torch.randn(3,6)
outputs

tensor([[ 0.1497,  0.5646,  1.4936, -1.1590, -1.3580,  0.4137],
        [-0.3466, -2.5903,  0.6336,  1.4549,  1.3155,  0.7850],
        [ 1.0674,  0.8205, -0.8584,  0.1572, -2.1006, -0.2919]])

In [7]:
mean= outputs.mean(dim=-1, keepdim=True)
mean

tensor([[ 0.0175],
        [ 0.2087],
        [-0.2010]])

In [8]:
sd= outputs.std(dim=-1, keepdim=True)
sd
#author uses outputs.var

tensor([[1.0889],
        [1.5122],
        [1.1687]])

In [9]:
normalized_outputs= (outputs-mean)/sd
normalized_outputs

tensor([[ 0.1215,  0.5025,  1.3556, -1.0804, -1.2631,  0.3639],
        [-0.3672, -1.8510,  0.2810,  0.8241,  0.7319,  0.3811],
        [ 1.0853,  0.8740, -0.5625,  0.3065, -1.6254, -0.0778]])

In [10]:
normalized_outputs.mean(dim=-1, keepdim=True)

tensor([[-1.9868e-08],
        [ 0.0000e+00],
        [-9.9341e-09]])

In [11]:
normalized_outputs.std(dim=-1, keepdim=True)

tensor([[1.],
        [1.],
        [1.]])

In [12]:
torch.set_printoptions(sci_mode=False)