<a href="https://colab.research.google.com/github/ainsley-snell/Data_Mining_CS290/blob/main/simple_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import tiktoken

In [ ]:
raw_text="This is my dog Hazel"
tokenizer= tiktoken.get_encoding("gpt2")
enc_text= tokenizer.encode(raw_text)
print(enc_text)

[1212, 318, 616, 3290, 42805]


In [ ]:
vocab_size= 4
output_dim= 8
inputs= torch.nn.Embedding(vocab_size, output_dim)
print(inputs.weight)

Parameter containing:
tensor([[-1.0583, -0.0852, -0.0109,  1.7738, -1.6722,  0.6944, -1.1482,  0.8530],
        [ 1.1920,  0.0608, -1.5753,  1.9308, -0.3620,  0.8919, -0.1951,  0.8675],
        [-1.2731, -0.6346, -0.0420, -1.5472, -0.8058,  0.8409,  1.7525,  0.3504],
        [-0.2306, -1.0688, -0.5420,  1.0409, -1.3454, -2.0214, -1.4396,  1.8541]],
       requires_grad=True)


In [ ]:
inputs= inputs.weight.data
inputs

tensor([[-1.0583, -0.0852, -0.0109,  1.7738, -1.6722,  0.6944, -1.1482,  0.8530],
        [ 1.1920,  0.0608, -1.5753,  1.9308, -0.3620,  0.8919, -0.1951,  0.8675],
        [-1.2731, -0.6346, -0.0420, -1.5472, -0.8058,  0.8409,  1.7525,  0.3504],
        [-0.2306, -1.0688, -0.5420,  1.0409, -1.3454, -2.0214, -1.4396,  1.8541]])

In [ ]:
inputs.shape

torch.Size([4, 8])

In [ ]:
for row in inputs:
    print(row.tolist())

In [ ]:
x= torch.Tensor([1.1,2.3])
y= torch.Tensor([3.4,-2.1])
torch.dot(x,y)

In [ ]:
query= inputs[2]
print(query)

In [ ]:
for i in range(len(inputs)):
    print(torch.dot(query,inputs[i]))

In [ ]:
attention_scores_2= torch.zeros(len(inputs))
for i in range(len(inputs)):
    attention_scores_2[i]=torch.dot(query,inputs[i])
print(attention_scores_2)

In [ ]:
#normalize attention scores using the softmax funtion to become weights:
#def softmax(x):
#    torch.exp(x)/ torch.exp(x).sum()

In [ ]:
attention_weights_2= torch.softmax(attention_scores_2, dim=0)
attention_weights_2

In [ ]:
attention_weights_2.sum()

In [ ]:
#use weights to create context vector
context_vector_2= torch.zeros(query.shape)
for i in range(len(attention_weights_2)) :
    context_vector_2 += attention_weights_2[i]* inputs[i]
context_vector_2

In [ ]:
inputs

tensor([[-1.0583, -0.0852, -0.0109,  1.7738, -1.6722,  0.6944, -1.1482,  0.8530],
        [ 1.1920,  0.0608, -1.5753,  1.9308, -0.3620,  0.8919, -0.1951,  0.8675],
        [-1.2731, -0.6346, -0.0420, -1.5472, -0.8058,  0.8409,  1.7525,  0.3504],
        [-0.2306, -1.0688, -0.5420,  1.0409, -1.3454, -2.0214, -1.4396,  1.8541]])

In [ ]:
inputs.T

tensor([[-1.0583,  1.1920, -1.2731, -0.2306],
        [-0.0852,  0.0608, -0.6346, -1.0688],
        [-0.0109, -1.5753, -0.0420, -0.5420],
        [ 1.7738,  1.9308, -1.5472,  1.0409],
        [-1.6722, -0.3620, -0.8058, -1.3454],
        [ 0.6944,  0.8919,  0.8409, -2.0214],
        [-1.1482, -0.1951,  1.7525, -1.4396],
        [ 0.8530,  0.8675,  0.3504,  1.8541]])

In [ ]:
#get all attention scores via matrix multiplication (inputs.T is transposed inputs)
attention_scores= inputs @ inputs.T
attention_scores

tensor([[ 9.5986,  4.3639, -1.1244,  6.2680],
        [ 4.3639,  9.3512, -3.4736,  3.0970],
        [-1.1244, -3.4736,  8.9694, -3.1046],
        [ 6.2680,  3.0970, -3.1046, 13.9789]])

In [ ]:
attention_weights= torch.softmax(attention_scores, dim=-1)
attention_weights

tensor([[9.6050e-01, 5.1182e-03, 2.1161e-05, 3.4358e-02],
        [6.7649e-03, 9.9133e-01, 2.6698e-06, 1.9056e-03],
        [4.1330e-05, 3.9450e-06, 9.9995e-01, 5.7052e-06],
        [4.4769e-04, 1.8786e-05, 3.8063e-08, 9.9953e-01]])

In [ ]:
attention_weights[0].sum()

tensor(1.0000)

In [ ]:
context_vectors=attention_weights @ inputs
context_vectors

tensor([[-1.0184, -0.1182, -0.0371,  1.7494, -1.6543,  0.6021, -1.1533,  0.8875],
        [ 1.1741,  0.0577, -1.5628,  1.9280, -0.3727,  0.8850, -0.2039,  0.8693],
        [-1.2731, -0.6345, -0.0421, -1.5470, -0.8058,  0.8409,  1.7523,  0.3504],
        [-0.2310, -1.0683, -0.5417,  1.0412, -1.3455, -2.0201, -1.4394,  1.8536]])