<a href="https://colab.research.google.com/github/ainsley-snell/Data_Mining_CS290/blob/main/simple_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

In [ ]:
# one way to make some typical input:
input = torch.randn( 1, 3 )
input

tensor([[0.7478, 0.5352, 1.8176]])

In [ ]:
input = torch.tensor([[ 1.0, 2.0, 3.0 ]])
input

tensor([[1., 2., 3.]])

In [ ]:

# a simple neural network:
model = nn.Sequential(
    # a layer that takes 3 inputs, gives 2 outputs
    nn.Linear( 3, 2 ),
    # a nonlinear activation function
    nn.ReLU(),
    # output layer takes 2 inputs, gives scalar output
    nn.Linear( 2, 1)
)

In [ ]:
model[0].weight.data = torch.tensor([[ 2.0, 1.0, -1.0 ],
                                     [ -2.0, -1.0, 1.0 ]])
model[0].weight.data

tensor([[ 2.,  1., -1.],
        [-2., -1.,  1.]])

In [ ]:
model[0].bias.data = torch.tensor([[0.0, 0.0]])

In [ ]:
input @ model[0].weight.data.T + model[0].bias.data

tensor([[ 1., -1.]])

In [ ]:
activation = nn.ReLU()
middle = activation( input @ model[0].weight.data.T + model[0].bias.data)
middle

tensor([[1., 0.]])

In [ ]:
middle @ model[2].weight.data.T + model[2].bias.data

tensor([[-0.5749]])

In [ ]:
model(input)

tensor([[-0.5749]], grad_fn=<AddmmBackward0>)