<a href="https://colab.research.google.com/github/ainsley-snell/Data_Mining_CS290/blob/main/trainable_attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import torch

In [21]:
inputs= torch.nn.Embedding(4,8)

In [22]:
inputs= inputs.weight
inputs

Parameter containing:
tensor([[ 2.5602,  0.4678,  0.3619, -1.2885, -0.4781,  0.3765,  0.0428,  0.5570],
        [-1.5875,  0.3160,  0.1094,  1.8715,  1.7058,  2.2737,  0.7470,  1.0993],
        [ 0.5303,  0.4413,  0.0099,  0.4032, -0.1358,  0.5920, -0.0742,  0.4739],
        [ 0.4147, -0.9960, -1.8196, -0.1461, -0.3499, -0.1309,  1.2607, -0.5800]],
       requires_grad=True)

In [23]:
inputs= inputs.data
inputs

tensor([[ 2.5602,  0.4678,  0.3619, -1.2885, -0.4781,  0.3765,  0.0428,  0.5570],
        [-1.5875,  0.3160,  0.1094,  1.8715,  1.7058,  2.2737,  0.7470,  1.0993],
        [ 0.5303,  0.4413,  0.0099,  0.4032, -0.1358,  0.5920, -0.0742,  0.4739],
        [ 0.4147, -0.9960, -1.8196, -0.1461, -0.3499, -0.1309,  1.2607, -0.5800]])

In [24]:
# set dimensions
d_in= 8
d_out= 6
# create weight matrices
W_q = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_k = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_v = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)

In [25]:
# choose an input vector and transform it into our query vector using W_q
query= inputs[2] @ W_q
query

tensor([1.1652, 0.9137, 1.3965, 1.0484, 1.2497, 0.9704])

In [26]:
# calculate attention scores using the keys generated by W_k:
keys= inputs @ W_k
values= inputs @ W_v
print("Keys:", keys)
print("Values:", values)

Keys: tensor([[ 2.0818,  0.5007,  0.7833,  2.2199,  2.0159,  1.3516],
        [ 2.4085,  4.9586,  2.7884,  2.9925,  2.3916,  2.1833],
        [ 1.1868,  1.1766,  0.9202,  1.4628,  1.2584,  0.7546],
        [-1.4885, -1.7099, -0.7886, -1.2880, -1.2909, -0.0891]])
Values: tensor([[ 1.8599,  1.2653,  1.2608, -0.0197,  2.7873,  1.9251],
        [ 1.3252,  3.7531,  4.3339,  4.0905,  2.6948,  2.4768],
        [ 1.0281,  1.1053,  1.3850,  0.6431,  1.6732,  1.4570],
        [-0.4627, -2.3411, -2.1264, -1.1522, -1.0086, -2.4902]])


In [27]:
attention_scores= query @ keys.T
attention_scores

tensor([10.1353, 19.4761,  7.5815, -7.4482])

In [29]:
attention_weights= torch.softmax(attention_scores, dim=-1)
attention_weights

tensor([8.7763e-05, 9.9991e-01, 6.8264e-06, 2.0271e-12])

In [30]:
attention_weights.sum()

tensor(1.)

In [31]:
context_vector= attention_weights @ values
context_vector

tensor([1.3252, 3.7529, 4.3336, 4.0901, 2.6948, 2.4767])